version: "2"
services:
  test:
    hostname: test
    image: tomcat:8
    volumes:
      - "./S2-057_war.war:/usr/local/tomcat/webapps/S2-057_war.war"
    ports:
      - "8080:8080"
    entrypoint:
      - "catalina.sh"
      - "run"
